### PR TITLE
Fwupd 1.8.12

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by 13r0ck** [comment]
@pop-os/quality-assurance bump

**Review by leviport — CHANGES_REQUESTED** [review]
I'm running into a dependency error with this update. If I just do `sudo apt upgrade`, it tells me that `fwupd` and `libfwupd2` were kept back. If I do a `full-upgrade`, it removes `libfwupdplugin5`.

And most importantly, when I update from Pop Shop, it errors out and gives me this message:
```
The following packages have unmet dependencies:
  libfwupdplugin5: Depends: libfwupd2 (= 1.8.0-1pop0~1673456498~22.04~41630ae) but 1.8.12-2~1680709885~22.04~6b07e09 is to be installed
```

**Comment by 13r0ck** [comment]
[19bc5a1](https://github.com/pop-os/fwupd/pull/24/commits/19bc5a11bffed0b48a28289fc333f18e0aef9846) should fix that

**Comment by leviport** [comment]
Apt is still unhappy for some reason.

Pop Shop error:
```
The following packages have unmet dependencies:
  libfwupdplugin5: Depends: libfwupd2 (= 1.8.0-1pop0~1673456498~22.04~41630ae) but 1.8.12-2~1682985193~22.04~19bc5a1 is to be installed
```

Other info:
```
$ sudo apt full-upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  libfwupdplugin5
The following NEW packages will be installed:
  jq libjq1 libonig5 libprotobuf-c1
The following packages will be upgraded:
  fwupd libfwupd2
2 upgraded, 4 newly installed, 1 to remove and 0 not upgraded.
Need to get 3,493 kB of archives.
After this operation, 184 kB disk space will be freed.
Do you want to continue? [Y/n] 
```

```
$ apt policy fwupd
fwupd:
  installed: 1.8.0-1pop0~1673456498~22.04~41630ae
  candidate: 1.8.12-2~1682985193~22.04~19bc5a1
  version table:
     1.8.12-2~1682985193~22.04~19bc5a1 1002
       1002 http://apt.pop-os.org/staging/fwupd-1-8-12 jammy/main amd64 packages
 *** 1.8.0-1pop0~1673456498~22.04~41630ae 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 packages
        100 /var/lib/dpkg/status
     1.7.9-1~22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 packages
     1.7.5-3 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 packages
```

**Comment by 13r0ck** [comment]
bummer. I'll see what I can do

**Comment by 13r0ck** [comment]
Ah, `Provides` didn't seem to be enough.  A full transitional package did the trick. I have this working on my machine with just `sudo apt upgrade`. This is ready for QA review again

**Review by n3m0-22 — APPROVED** [review]
This is working correctly now.

Tested on lemp11 and Dev One

Working:
 - `apt upgrade` and `apt full-upgrade`
 - `fwupdmgr` CLI and Settings detects Launch Heavy
 - Firmware on Dev One upgrade/downgrade from CLI and Settings

**Review by leviport — APPROVED** [review]
@n3m0-22 already tested it, but I double-checked since my review was requested, and I concur with his findings.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
