### PR TITLE
Add System76 launch_2

### PR DESCRIPTION
**Pull request by jackpot51**
Will need to upload firmware before this can be tested

### CODE REVIEW

**Comment by leviport** [comment]
I believe this is the last thing needed for launch_2. Has firmware been uploaded for me to test?

**Review by mmstick — DISMISSED** [review]

**Comment by jackpot51** [comment]
> I believe this is the last thing needed for launch_2. Has firmware been uploaded for me to test?

It has not.

**Comment by leviport** [comment]
Both boards are now in the Embargo remote for testing.

**Review by mmstick — APPROVED** [review]

**Comment by XV-02** [comment]
When testing updating launch_2, writing the firmware update with fwupdmgr seemed to abort with `not supported` before exiting the process. 

passing `fwupdmgr update [Device ID]`

yielded:

```

Decompressing…           [-                                      ]Devices with no available firmware updates: 
 • WDC WDS100T2B0C-00PXH0
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Launch Configurable Keyboard (launch 2) from 0.7.103-4037-gd235be    ║
║ to 0.7.103-4038-g223cd2?                                                     ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release provides the first production firmware version to be     ║
║ used in manufacturing                                                        ║
║                                                                              ║
║ Launch Configurable Keyboard (launch 2) and all connected devices may not    ║
║ be usable while updating.                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: y
Downloading…             [***************************************]
Downloading…             [***************************************]
Authenticating…          [***************************************]
Action Required: To ensure you have physical access, Launch Configurable Keyboard (launch 2) needs to be manually unlocked. Please press Left Ctrl+Right Ctrl+Esc to unlock and re-run the update.
Writing…                 [***********                            ]not supported
```

This behaviour happened reliably when trying to update from production's initial flash. Unsurprisingly, this behaviour also persists in our firmware settings page.

On Launch_heavy_1, fwupdmrg correctly recognized the device, and was able to report that the firmware was the latest available.

**Comment by XV-02** [comment]
Not positive it'll be specifically helpful, but the verbose output of the update command:
[VerboseFwupdmgr.log](https://github.com/pop-os/fwupd/files/10197214/VerboseFwupdmgr.log)

**Comment by jackpot51** [comment]
Going to bypass the firmware update test so we can have something showing the current version.

**Pull request merged**
