### PR TITLE
Add launch_lite_1

### PR DESCRIPTION
**Pull request by jackpot51**
Use with https://github.com/system76/launch/pull/55. Includes #11, and should require `master` staging repo for `fwupd-efi`

### CODE REVIEW

**Comment by jackpot51** [comment]
@pop-os/quality-assurance @pop-os/engineering I still need reviews on this

**Comment by leviport** [comment]
Are the focal build failures going to be an issue?

**Comment by jackpot51** [comment]
I rewrote this to match https://github.com/fwupd/fwupd/pull/4466

**Comment by jackpot51** [comment]
The firmware is now on LVFS stable, so it should be ready to go

**Comment by leviport** [comment]
This isn't working on Focal (probably because of the build errors), but it is looking good on Jammy and Impish.

**Comment by leviport** [comment]
Should Lite be showing up as a "Launch Configurable Keyboard (launch lite 1)"?

**Comment by jackpot51** [comment]
Yep

**Review by leviport — APPROVED** [review]
I think this looks good, both with Launch Lite, and with the rebase.

**Pull request merged**
