### PR TITLE
thelio_io_2 (and launch_3/launch_heavy_3)

### PR DESCRIPTION
**Pull request by jackpot51**
Updates to the latest debian release (1.9.4-2) and applies the upstream thelio-io PR.

Redo of #27 with only jammy.

### CODE REVIEW

**Comment by jackpot51** [comment]
Intermittent build issues might be solved by https://github.com/fwupd/fwupd/pull/6131

**Comment by leviport** [comment]
With this, fwupd sees Heavy as a supported device (with no updates available), but trying to install the .cab file with fwupdtool gives me some kind of error:

```
$ sudo fwupdtool install-blob launch_heavy_3_0.21.0-69-gacc420.cab 29627b6877d3b89cccee135287435fde986fee98
Loading…                 [-                                      ]20:26:13.487 FuPluginUefiCapsule  SMBIOS BIOS Characteristics Extension Byte 2 is invalid -- UEFI Specification is unsupported, but /sys/firmware/efi exists: System does not support UEFI mode
Action Required: To ensure you have physical access, Launch Heavy Configurable Keyboard (launch heavy 3) needs to be manually unlocked. Please press Left Ctrl+Right Ctrl+Esc to unlock and re-run the update.
Decompressing…           [********************                   ]
constant Uf2.magic0 was not valid, expected 0x0A324655
```
It stops after the "needs to be unlocked" message, then when I unlock it, it freezes up and becomes unresponsive until I unplug and re-plug it. This was with heavy_3. I will test launch_3 next, just in case it's different.

**Comment by leviport** [comment]
Yeah, exactly the same message with launch_3

**Comment by leviport** [comment]
I see Io v2 in `fwupdmgr get-devices`, but not in the "firmware" section of Gnome Control Center. What am I doing wrong? Logitech Unifying Receivers are showing up as expected.

**Review by leviport — APPROVED** [review]
This looks good with Io v2

**Pull request merged**
