### PR TITLE
Fwupd 1.8.0 (20.04 only)

### PR DESCRIPTION
**Pull request by jackpot51**
Backport of https://github.com/pop-os/fwupd/pull/17 to 20.04

### CODE REVIEW

**Comment by n3m0-22** [comment]
This has conflicts that need to be resolved for testing.

**Comment by XV-02** [comment]
> This has conflicts that need to be resolved for testing.

@n3m0-22 Can you expand on that? What specific conflicts are you referring to?

**Comment by leviport** [comment]
Since this is a rebase, file conflicts are expected. The real problems are the build failures.

**Comment by jackpot51** [comment]
Looking into build issues today.

**Comment by jackpot51** [comment]
I don't think the patches required to get this working on 20.04 are worth it. We could instead drop our custom fwupd version for Ubuntu's at some point. Backports of libqrtr-glib and meson would be required, at the very least. I have not made it past that.

**Pull request closed without merging**
