### PR TITLE
fwupd 1.5.8

### PR DESCRIPTION
**Pull request by jackpot51**
This updates fwupd to 1.5.8. It will be force pushed to master when approved
Requires https://github.com/pop-os/firmware-manager/pull/91

### CODE REVIEW

**Comment by jackpot51** [comment]
Ignore build failures on bionic, it will not go to bionic

**Comment by bflanagin** [comment]
The unified receiver that I use to test is no longer being removed from the list of devices after removing it from the system. This seems to be a regression with 1.5.7 but there seems to be issues with my unified receiver.

Then there is this: 

```
Update failure is a known issue, visit this URL for more information: https://github.com/fwupd/fwupd/wiki/LVFS-Triaged-Issue:-Unifying:-did-not-come-back
 ``` 
Which happens when I try to downgrade the receiver in order to check if I can update the driver. Triggered when using `fwupdmgr downgrade fb1a5fd6e7d8cbf5d5a2ba7df68aee106ce41027 { Unifying Receiver } `

**Comment by leviport** [comment]
I'm not seeing my Logitech receivers appear in the menu, either before or after this patch. Tested on pang10 and oryp6. Will test more devices later.

**Comment by jackpot51** [comment]
```
This is fixed by fwupd versions >= 1.5.8, which increases the timeout for the device. On older versions you can remove the device and plug it back in to complete the update.
```

I can try pulling 1.5.8

**Comment by jackpot51** [comment]
Now this brings in 1.5.8 as packaged by Ubuntu for 21.04

**Comment by bflanagin** [comment]
Much better in 1.5.8 firmware interface both GUI and CLI are updating as expected. Downgraded and then upgraded unified receiver from the command line without fail.

However, on attempting to upgrade from the UI I received an error message:
Screenshot from 2021-04-01 07-11-26

**Comment by jackpot51** [comment]
@mmstick I think what @bflanagin is reporting is a firmware-manager issue, can you take a look?

**Comment by jackpot51** [comment]
Now that Firmware Manager is fixed, is this ready to be released?

**Comment by jackpot51** [comment]
@bflanagin is this good to be released?

**Review by bflanagin — APPROVED** [review]

**Comment by bflanagin** [comment]
Shoot, forgot to go back to this one after approving the other. Need to get my notification sorted for things like this.

**Pull request merged**
