### PR TITLE
fwupd 1.7.4

### PR DESCRIPTION
**Pull request by jackpot51**
https://github.com/fwupd/fwupd/releases/tag/1.7.4

Requires a new package to build: https://github.com/pop-os/fwupd-efi

### CODE REVIEW

**Review by 13r0ck — CHANGES_REQUESTED** [review]
21.10 will not upgrade without using `apt full-upgrade`
on 21.10 it does work correctly after using `full-upgrade`, but Levi asked that I request changes for that, as `full-upgrade` confuses pop!_shop.

20.04 won't update at all, but that might be user error on my part. Adding the `fwupd-1.7.4` branch then running `sudo apt full-upgrade` doesn't upgrade it. `apt policy fwupd` doesn't recognize the new version either. But I'm not sure what I might be missing

**Comment by jackpot51** [comment]
This will also require `master` staging branch for the new fwupd-efi package

**Comment by 13r0ck** [comment]
Just to ping here from the conversation on mattermost a few days ago, adding the `master` branch doesn't fix the issue. The same symptoms occur. On the master branch there is no install candidate for `fwupd-efi`.

I tested again today to double check.

**Comment by jackpot51** [comment]
I believe https://github.com/pop-os/fwupd-efi/commit/f30da97fb3eb278f14cb0e0b9eb1d949b5401c0a will fix this.

**Comment by 13r0ck** [comment]
That fixed the issue on 21.10, but not on 20.04,

20.04 is till broken. It doesn't update,
Trying both a `apt upgrade` and `apt full-upgrade` return:
```
The following packages have been kept back:
    fwupd-signed
```

**Comment by jackpot51** [comment]
Review with #12

**Pull request closed without merging**
